//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
namespace RegistrationAndLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemoClass
    {
        [Display (Name = "Class Id")]
        public int ClassId { get; set; }

        [Display(Name = "Class Name")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please Enter Class Name.")]
        public string ClassName { get; set; }

        [Display(Name = "Total Hours")]
        [Range(0, int.MaxValue, ErrorMessage = "Please enter valid integer Number")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please Enter Total Hours.")]
        public int NofHoure { get; set; }
    }
}
